spring:
  application:
    name: subgraph-principals
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/imdb}

dgs:
  graphql:
    schema-locations: classpath:schema/**
    federation:
      enabled: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
